In [4]:
## Assignment 1

#In this assignment you will program some functions using Python. The idea is to learn how you can write some basic functions and perform basic operations.

In [5]:
import numpy as np

# We are going to implement some functions/constants that our calculator / `numpy` / Google has.

#### Exercise 1: Write a function to calculate the factorial of a number `n`

The factorial of a number is represented by using the exclamation sign, for example, the factorial of $3$ is represented as $3!$. You can see how the factorial of a number N is calculated in the following examples:

$$1! = 1$$

$$2! = 2 x 1 = 2$$

$$3! = 3 x 2 x 1 = 6$$

The general formula is:

$$n! = n (n-1)!$$

$$1! = 1$$

$$0! = 1$$

You can use either an iterative approach (with for or while loops) or a recursive approach.

In [6]:
#Solution 1
def fact(n):
    factorial = n
    if n == 0:
        return 1
    else:
        while n > 1:
            factorial *= (n - 1)
            n -= 1
            if n == 1:
                return(factorial)

In [10]:
fact(6)

720

In [11]:
#Solution 2
def factorial (n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
    
factorial(int(input("Enter a number: ")))

Enter a number: 6


720

#### Exercise 2: Approximate number e

Euler's number, the number `e` is a constant number which is the base of the natural logarithm ($ln$). It is approximately 2.71828 and it can be calculated as the sum of the following infinite series:

$$e \approx \sum _ { k = 0 } ^ { \infty } \frac { 1 } { k ! } = \frac{1}{1} + \frac{1}{1} + \frac{1}{1x2}+ \frac{1}{1x2x3}+ \frac{1}{1x2x3x4} + \ldots$$

We know that infinity is very big, but, we can approximate the number, let's say, until $k=100$. Can you?

In [19]:
def approximate_e (k = 100):
    e= 0
    for i in range(k):
        e = e + (1/factorial(i))
    return e

In [20]:
e = approximate_e()
e

2.7182818284590455

#### Additional/Optional exercise:

Which is the difference between the approximations between, e.g., $k=20$ and $k=21$? How is that difference as $k$ becomes bigger?

In [ ]:
#YOUR CODE HERE (OPTIONAL)

#### Exercise 3: Approximate Square root using the Babylonian method

Now we are interested in calculating the square root of any number. It may seem trivial, but it is not so easy. Think, for instance, which is the square root of $60$?

I googled how to do it, and I found nice methods for doing it. Check this [Wikipedia page](https://en.wikipedia.org/wiki/Methods_of_computing_square_roots)!

In this exercise you have to implement the Babylonian method, which calculates the square roots quite well. As with the number `e`, this result is reached when the function reaches infinity. Here you should also work for $k=100$ iterations.

The method initializes $x_0$ with the approximate square root of $S$. In our case, in order to ensure that everybody gets the same answer, we will initialize the value with $S$.


$$x _ { 0 } = S $$

$$x _ { k + 1 } = \frac { 1 } { 2 } \left( x _ { k } + \frac { S } { x _ { k } } \right) $$

$$\sqrt { S } = \lim _ { k \rightarrow \infty } x _ { k }$$


In [ ]:
def appr_sqrt(S):
    estimate = S
    error = 0
    for i in range(100): 
        error = (S - S**2)/(2*S+error)
    estimate += error
    return estimate 

In [ ]:
appr_sqrt(60)

#### Additional/Optional exercise:

What happens if we initialize the $x_0$ with different values?

In [ ]:
def appr_sqrt(S, different_estimate):
    estimate = different_estimate
    error = 0
    for i in range(100): 
        error = (S - estimate**2)/(2*estimate+error)
    estimate += error
    return estimate 
appr_sqrt(100, 10), appr_sqrt(100, 20), appr_sqrt(100, 30)

#### Exercise 4: Approximate the number $\pi$

The number $\pi$ is an amazing number! It was originally defined as the ratio of a circle's circumference to its diameter, and now it has some other equivalent definitions.

We saw an approximation for estimating the number by using random numbers (this is also known as a Montecarlo simulation), but today we will implement another formula for approximating it. Here it is:

$$v a l = \sum _ { k = 0 } ^ { \infty } \frac { (- 3) ^ { - k } } { 2 k + 1 }$$

$$\pi \approx val \cdot \sqrt { 12 }$$

Again, this is an infinite series, which should approximate the number fairly well for high numbers. But, as in previous cases, in order to have a coherent result, we will calculate the value of $\pi$ after $k=100$ iterations, and using the previously created `appr_sqrt` function. 

In [ ]:
def appr_pi ():
    value = 0
    for i in range(100):
        value += (-3)**(-i) / (2*i + 1)
    return value * appr_sqrt(12, 4)

In [ ]:
appr_pi()

#### Exercise 5: Matrix multiplication with lists

We know how important matrix multiplication is for Machine Learning, Deep Learning and algebra, in general. We also know that there is a wonderful function in the package `numpy` that can do that for us (`np.dot`). But if we were to use that function, this exercise would not be fun!

So, in this excercise you are asked to implement a matrix multiplication function `matrix_multiply(m1, m2)` that takes two numpy matrices as arguments and returns the matrix product of these in a new matrix. The function should work element by element without calling any vectorized methods. Although numpy library already implements matrix multiplication, your implementation cannot use any part of the numpy library, with the exceptions noted below:

  * `.shape` to get the size of a matrix;
  * `np.zeros((n, m))` to create a new $n$ by $m$ matrix; and
  * the `[i, j]` indexing syntax to retrieve or set the value of cell $(i, j)$.

Below are defined matrices $X, Y$ and $Z$.

Implement the function matrix_multiply(m1, m2) and test it by computing the products $M_1M_2$ and $M_3M_4$.


In [12]:
X = np.array([[6,7,7,8],[4,3,3,3]])
Y = np.array([[1,3,5],[2,4,9],[8,9,0],[3,3,3]])
Z = np.array([[10,13,45,11],[65,24,42,98],[1,1,2,0],[4,2,1,2]])

In [13]:
X.shape,Y.shape,Z.shape
print(X)
print(Y)
print(Z)

[[6 7 7 8]
 [4 3 3 3]]
[[1 3 5]
 [2 4 9]
 [8 9 0]
 [3 3 3]]
[[10 13 45 11]
 [65 24 42 98]
 [ 1  1  2  0]
 [ 4  2  1  2]]


In [14]:
def matrix_multiply(m1, m2):
    
    assert m1.shape[1] == m2.shape[0]
    
    out = np.zeros((m1.shape[0], m2.shape[1]), dtype=m1.dtype)
    
   
    component_vector_size = m1.shape[1]
    number_of_rows = m1.shape[0]
    number_of_columns = m2.shape[1]
    
    for i, row in enumerate(out):
        for j, cell in enumerate(row):
            for a in range (m1.shape[1]):
                out[i][j] += m1[i][a] * m2[a][j]
  
    return out

In [15]:
print(matrix_multiply(X,Y))
print(np.dot(X,Y))

[[100 133 117]
 [ 43  60  56]]
[[100 133 117]
 [ 43  60  56]]


In [16]:
print(matrix_multiply(X,Z))
print(np.dot(X,Z))

[[554 269 586 768]
 [250 133 315 344]]
[[554 269 586 768]
 [250 133 315 344]]


In [17]:
print(matrix_multiply(Z,Y))
print(np.dot(Z,Y))

[[429 520 200]
 [743 963 835]
 [ 19  25  14]
 [ 22  35  44]]
[[429 520 200]
 [743 963 835]
 [ 19  25  14]
 [ 22  35  44]]


#### Additional exercise:

Implement Matrix Multiplication using only lists, without using any options that the `numpy` package gives you. Can you do it?

In [18]:
#YOUR CODE HERE (OPTIONAL) 